Created tasks, added CR of CRUD for tasks;
MaximStadnikov/task_tracker pull request #4
Opened 2022-09-25 21:40 UTC by Ragnoji

### Summary

A brief description of the pull request.

### How it works

Screenshots/screencasts of the pull request introduced functionality.

### Test plan

List of steps to manually test introduced functionality:

- Log in
- Go to http://localhost:3000

### Deploy notes

Notes regarding deployment the contained body of work.
These should note any db migrations, services, scripts, etc.

### Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My pull request is shorter than 500 lines

2022-09-25 21:42 UTC, Ragnoji commented
Это Степанов Алмаз из 11-105

2022-09-27 15:59 UTC, MaximStadnikov requested changes

2022-09-27 15:59 UTC, MaximStadnikov commented on .idea/.gitignore
> +# Default ignored files
Этот файл не стоит добавлять в ПР

2022-09-27 15:59 UTC, MaximStadnikov commented on Gemfile
> +# Transpile app-like JavaScript. Read more: https://github.com/rails/r
Опечатки тоже не стоит добавлять :)

2022-09-27 15:59 UTC, MaximStadnikov commented on app/helpers/tasks_helper.rb
> +module TasksHelper
этот файл нам не нужен (мы его нигде не используем)

2022-09-27 16:03 UTC, MaximStadnikov commented
@Ragnoji не пугайся большому количеству комментариев - у тебя пара лишних файлов, ошибок нет (не считая лишнего файла `views/tasks/create.html.erb`. Остальные комментарии - это замечания на добавление ссылок. Ты молодец, что подумал про навигацию по сайту! Но это немного рановато, мы будем добавлять это позже. Как исправишь мои комментарии, дз будет принято.

Хорошая работа!

2022-09-28 08:33 UTC, Ragnoji commented on Gemfile
> +# Transpile app-like JavaScript. Read more: https://github.com/rails/r
А в чем опечатка? Это же webpacker, эта строка сама сгенерировалась

2022-09-28 12:21 UTC, Ragnoji reviewed
Checked through comments and removed redundant files/lines of code

2022-09-28 12:21 UTC, Ragnoji commented on Gemfile
> +# Transpile app-like JavaScript. Read more: https://github.com/rails/r
```suggestion
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
```

2022-09-28 12:21 UTC, Ragnoji commented on app/views/projects/edit.html.erb
>  <h1>Editing Project</h1>
```suggestion
<h1>Editing Project</h1>
```

2022-09-28 12:21 UTC, Ragnoji commented on app/views/projects/new.html.erb
>  <h1>New Project</h1>
```suggestion
<h1>New Project</h1>
```

2022-09-28 12:21 UTC, Ragnoji commented on app/views/tasks/new.html.erb
> +<h1>New Task</h1>
```suggestion
<h1>New Task</h1>
```

2022-09-28 12:21 UTC, Ragnoji commented on app/views/tasks/show.html.erb
> +<p id="notice"><%= notice %></p>
```suggestion
<p id="notice"><%= notice %></p>
```

2022-09-28 12:55 UTC, MaximStadnikov requested changes

2022-09-28 12:55 UTC, MaximStadnikov commented on app/views/projects/show.html.erb
> +<%= link_to "Tasks", tasks_path %>
@Ragnoji этот комментарий всё еще актуален

2022-09-28 12:56 UTC, MaximStadnikov commented
И еще один комментарий - не нужно каждый файл в отдельный коммит добавлять. Все исправления можно поместить в один коммит

2022-09-29 16:11 UTC, MaximStadnikov approved these changes

2022-10-09 20:07 UTC, merged