Create new task
MaximStadnikov/task_tracker pull request #6
Opened 2022-09-27 15:25 UTC by DataJoshua

### Summary

A brief description of the pull request.

### How it works

Screenshots/screencasts of the pull request introduced functionality.

### Test plan

List of steps to manually test introduced functionality:

- Log in
- Go to http://localhost:3000

### Deploy notes

Notes regarding deployment the contained body of work.
These should note any db migrations, services, scripts, etc.

### Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My pull request is shorter than 500 lines

2022-10-04 22:06 UTC, DataJoshua commented
Д3 сделал в branch

2022-10-05 18:31 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +    end
Why you duplicate task_params?

2022-10-05 18:33 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +      @project = Project.find(params[:project_id])
It is okay, but in the assignment I asked to use bang version of `find_by` method

2022-10-05 18:33 UTC, RasimKhusaenov commented on app/helpers/tasks_helper.rb
> +end
Redundant. We don't need it.

2022-10-05 18:34 UTC, RasimKhusaenov commented on app/javascript/packs/application.js
> +/* eslint no-console:0 */
Don't edit this file

2022-10-05 18:35 UTC, RasimKhusaenov commented on app/views/projects/index.html.erb
> +        <td><%= link_to 'Destroy', project, method: :destroy, data: { confirm: 'Are you sure?' } %></td>
Does it work?

2022-10-05 18:37 UTC, RasimKhusaenov commented on app/views/tasks/_form.html.erb
> +        <input type="date" name="task[deadline_at]" id="task[deadline_at]" value=<%= Time.now + 7.days %> />
It is incorrect. In this implementation, the user can change the default deadline value

2022-10-05 18:40 UTC, RasimKhusaenov commented on app/views/tasks/index.html.erb
> +<%= link_to "Back", @project %>
Incorrect link. We should back to project tasks

2022-10-05 18:40 UTC, RasimKhusaenov commented on app/views/tasks/index.html.erb
> +<%= link_to "Create Task", new_project_task_path %>
Does it work?

2022-10-05 18:41 UTC, RasimKhusaenov commented on app/views/tasks/show.html.erb
> +    <%= link_to 'back', project_tasks_path %>
Does it work?

2022-10-05 18:41 UTC, RasimKhusaenov commented on config/database.yml
> +  adapter: postgresql
Don't edit this file

2022-10-05 18:42 UTC, RasimKhusaenov commented on db/migrate/20220927132936_create_tasks.rb
> +      t.datetime :deadline_at, :default => Time.now
Remove default. It sets default value to date when migration was migrated

2022-10-05 18:43 UTC, RasimKhusaenov commented on package.json
> +    "bundle": "^2.1.0",
Why?

2022-10-05 18:52 UTC, RasimKhusaenov commented on app/models/task.rb
> +    validates :name, presence: true
:+1:

2022-10-05 18:52 UTC, RasimKhusaenov commented on app/views/tasks/index.html.erb
> +</ul>
There should be a table like the projects. With "Show", "Edit", "Destroy" buttons.

2022-10-05 18:52 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +  before_action :set_project
Do you need it everywhere?

2022-10-16 16:02 UTC, RasimKhusaenov commented
⚠️ You should do another HWs in another branch, hand it in another PR.

2022-10-16 16:51 UTC, DataJoshua commented
okay

2022-10-22 07:28 UTC, RasimKhusaenov requested changes

2022-10-22 07:28 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +    @task = @project.tasks.find(:id)
Does it work?

2022-10-22 07:28 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +  before_action :set_task, only: %i[show edit update destroy]
You don't use it anywhere, but you should use it almost everywhere

2022-10-22 07:28 UTC, RasimKhusaenov commented on app/views/projects/show.html.erb
> +<%= link_to 'tasks', [@project, @project.tasks.build] %>
Does it work?

2022-10-22 07:28 UTC, RasimKhusaenov commented on app/views/tasks/new.html.erb
> +<%= render "form", task: @project.tasks.build %>
Use task from controller

2022-10-22 07:28 UTC, RasimKhusaenov commented on db/migrate/20220927132936_create_tasks.rb
> +      t.string :project_id
Use reference, not string

2022-10-22 07:28 UTC, RasimKhusaenov commented on app/views/tasks/index.html.erb
> +            </tr>
Why you need turbo_method?

2022-10-22 07:28 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +    if @task.destroy
Why we need this condition?

2022-10-23 06:57 UTC, RasimKhusaenov requested changes

2022-10-23 06:57 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +    redirect_to project_tasks_path, notice: "Project was successfully destroyed."
You should redirect to deleted task's project page

2022-10-23 06:57 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +    @tasks = @project.tasks.all
`All` is redundant here
```suggestion
    @tasks = @project.tasks
```

2022-10-23 06:57 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +    @task = @project.tasks.create(task_params)
What happens if I try to create a task with an empty name?

2022-10-23 06:57 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +    params.require(:task).premit(:title, :name, :description)
Why you duplicate task_params?

2022-10-23 06:57 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +    @project = Project.find(params[:project_id])
It is okay, but in the assignment I asked to use bang version of find_by method

2022-10-23 06:57 UTC, RasimKhusaenov commented on app/controllers/tasks_controller.rb
> +    @task = Task.find(params[:id])
It is okay, but in the assignment I asked to use bang version of find_by method

2022-10-23 06:57 UTC, RasimKhusaenov commented on db/migrate/20221022093453_add_reference_to_tasks.rb
> +    add_reference :tasks, :project, foreign_key: true
Not in new migration! You just added migration in this PR, it's not in the project yet. Therefore, you should change the existing one, and not produce new ones.

2022-10-30 11:49 UTC, closed without merging