HW2
MaximStadnikov/task_tracker pull request #7
Opened 2022-09-30 15:33 UTC by RafaelKhammadeev

### Summary

A brief description of the pull request.

### How it works

Screenshots/screencasts of the pull request introduced functionality.

### Test plan

List of steps to manually test introduced functionality:

- Log in
- Go to http://localhost:3000

### Deploy notes

Notes regarding deployment the contained body of work.
These should note any db migrations, services, scripts, etc.

### Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My pull request is shorter than 500 lines

2022-10-04 12:46 UTC, MaximStadnikov requested changes

2022-10-04 12:46 UTC, MaximStadnikov commented on .idea/.gitignore
> +# Default ignored files
Папку .idea и все файлы в ней не нужно добавлять в ПР. Это файлы среды разработки и к проекту они никак не относятся. В следующих коммитах просто не добавляй эти файлы

2022-10-04 12:46 UTC, MaximStadnikov commented on Gemfile
> -gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
зачем ты убрал эту строчку?

2022-10-09 20:25 UTC, RafaelKhammadeev commented on Gemfile
> -gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
Ну я видео посмотрел, там сказали эта штука не нужно, типо она нужна только для тех кто использует windows

2022-10-09 20:25 UTC, RafaelKhammadeev commented on .idea/.gitignore
> +# Default ignored files
Понял принял

2022-10-17 07:49 UTC, closed without merging